# Python image (lightweight)
FROM python:3.10-slim

# Define working directory 
WORKDIR /app

# Copy requirements.txt file to the container
COPY requirements.txt .

# Isntall dependencies 
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# copy application code to the working directory
COPY api.py .
COPY favicon.ico .


# Copy directories and files to te app directory
COPY model /app/model
COPY pipeline /app/pipeline
COPY lib /app/lib
COPY static /app/static


# Export 8000 port that is used by uvicorn
EXPOSE 8000


# Define command to execute application
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]

# Optionnal : add metadata
LABEL maintainer="Alexandre Kavadias <kavadias.alexandre@gmail.com>"
LABEL description="Application FastAPI to make real estate prediction over Belgium country"
