services:
  - type: web
    name: immi-predict-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10